cronJob:
  name: kured-reboot-cronjob
  schedule: "0 0 31 2 *"
  suspend: true
  image: 
    repository: bitnami/kubectl
    tag: latest
  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m 
      memory: 256Mi
  annotation: weave.works/kured-reboot-in-progress
  rebootStartDelay: 60
  nodeReadyTimeout: 15m
  nodeDelay: 60
  checkRebootRequired: false